version: "3.8"

services: 
    db:
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - db-data:/data/db
        command: --serviceExecutor adaptive
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
            MONGO_INITDB_DATABASE: ${DB_DATABASE}

    mongo-express:
        image: mongo-express:latest
        restart: unless-stopped
        environment:
            ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
            ME_CONFIG_MONGODB_SERVER: db
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
        ports:
        - 8888:8888        

    api:
        build:
            context: ./src
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        environment: 
            PORT: ${PORT}

            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            AUTH_SOURCE: ${AUTH_SOURCE}
            CONNECTION_MODE: ${CONNECTION_MODE}

            COOKIE_SECRET: ${COOKIE_SECRET}
            ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
            REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}

            SEED_DIR: ${SEED_DIR}
        volumes: 
            - /home/node/app/node_modules
            - ./src:/home/node/app
        ports: 
            - ${PORT}:${PORT}

volumes:
    db-data: